### ISSUE TITLE
No ethernet

### ISSUE THREAD

**Issue by dfa1234** [BradenM/Hackintosh-7700k-R9_390-iGPU#2]
Hi, You don't know how you help me.
Just explaining.
I have the same processor, not same motherboard, mine is gigabite gaming z270, but your configuration save my life. I absolutely needed to update to high sierra, for the new xcode version, but the screen what flinketing/blinking.
Only problem was no ethernet connection.
Anyway I just put *AtherosE2200Ethernet.kext* file in the kext folder and my network come back!
Everything is good except i have usb 3 at usb 2 speed, it seem related to the issue you wrote.
Also bluetooth audio system is connected but no playing audio, but internal speaker are working so not sure if the problem is in the mac or not. It's no a big problem neither.
Anyway I'm so gratefull.

**Comment by BradenM** [comment]
Thanks! I'm glad I could help out. You actually made me realize something pretty important haha, once VirtualSMC is installed, your Kexts are no longer directly loaded from CLOVER/EFI, they need to be placed directory inside the /Library/Extensions folder (and then repaired, which I just run `repair_kexts` in tools.sh to do). So, due to this I actually forgot to reference the Kexts I had installed in /L/E. I had directly installed `IntelMausiEthernet.kext` for internet access, so I'm sorry I didn't have one available in the repo, but I'm glad you figured it out!

Anyways, I went ahead and added the missing Kexts, which includes `GenericUSBXHCI.kext`, which should fix your USB 3 issues.
> Also make sure you have the [USB 10.13.4+ by PMHeart Patch](https://hackintosher.com/guides/hackintosh-high-sierra-10-13-4-update-guide/#usb) enabled

As for audio, I don't personally use bluetooth so I can't say for sure, but in order to have any sound at all I followed [this guide](https://www.tonymacx86.com/threads/applehda-realtek-audio-guide.234732/#post-1606764). 

Let me know if you have any further issues, good luck!
